// <auto-generated />
using System;
using Chapter3finalredone.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chapter3finalredone.Migrations
{
    [DbContext(typeof(LoggingContext))]
    [Migration("20240806153409_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Description = "A squat is a strength exercise that involves lowering the hips from a standing position and then standing back up.",
                            ExerciseName = "Squats"
                        },
                        new
                        {
                            ExerciseId = 2,
                            Description = "The bench press is a compound exercise that targets the muscles of the upper body.",
                            ExerciseName = "Bench Press"
                        },
                        new
                        {
                            ExerciseId = 3,
                            Description = "The bent-over row is an exercise you can do with dumbbells to work the muscles in the back of the shoulder",
                            ExerciseName = "Row"
                        },
                        new
                        {
                            ExerciseId = 4,
                            Description = "A barbell curl is a variation of the biceps curl that uses a weighted barbell. ",
                            ExerciseName = "Barbell Curl"
                        });
                });

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkoutLogId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "killerclutch@gmail.com",
                            Reason = "Lose weight.",
                            UserName = "Joshua555"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Random616@gmail.com",
                            Reason = "Gain weight.",
                            UserName = "Random616"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "CoolBeans83@gmail.com",
                            Reason = "I want to jump higher.",
                            UserName = "CoolBeans83"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "Fitnessguy454@gmail.com",
                            Reason = "I want to fill out shirts.",
                            UserName = "Fitnessguy454"
                        });
                });

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.WorkoutLog", b =>
                {
                    b.Property<int>("WorkoutLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutLogId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutLogId");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            WorkoutLogId = 1,
                            Date = new DateOnly(2021, 10, 1),
                            Notes = "I struggled with leg day.",
                            UserId = 1
                        },
                        new
                        {
                            WorkoutLogId = 2,
                            Date = new DateOnly(2021, 10, 2),
                            Notes = "I did good on squats.",
                            UserId = 2
                        },
                        new
                        {
                            WorkoutLogId = 3,
                            Date = new DateOnly(2021, 10, 1),
                            Notes = "My form on front rows needs improvement.",
                            UserId = 2
                        },
                        new
                        {
                            WorkoutLogId = 4,
                            Date = new DateOnly(2021, 10, 2),
                            Notes = "I felt really motivated today.",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.WorkoutLogExercise", b =>
                {
                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutLogId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("workoutLogExercises");

                    b.HasData(
                        new
                        {
                            WorkoutLogId = 1,
                            ExerciseId = 3
                        },
                        new
                        {
                            WorkoutLogId = 1,
                            ExerciseId = 2
                        },
                        new
                        {
                            WorkoutLogId = 2,
                            ExerciseId = 1
                        },
                        new
                        {
                            WorkoutLogId = 2,
                            ExerciseId = 4
                        },
                        new
                        {
                            WorkoutLogId = 3,
                            ExerciseId = 2
                        },
                        new
                        {
                            WorkoutLogId = 3,
                            ExerciseId = 4
                        },
                        new
                        {
                            WorkoutLogId = 4,
                            ExerciseId = 3
                        },
                        new
                        {
                            WorkoutLogId = 4,
                            ExerciseId = 1
                        });
                });

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.User", b =>
                {
                    b.HasOne("Chapter3finalredone.Models.DomainModels.WorkoutLog", null)
                        .WithMany("Users")
                        .HasForeignKey("WorkoutLogId");
                });

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.WorkoutLog", b =>
                {
                    b.HasOne("Chapter3finalredone.Models.DomainModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.WorkoutLogExercise", b =>
                {
                    b.HasOne("Chapter3finalredone.Models.DomainModels.Exercise", "Exercise")
                        .WithMany("WorkoutLogExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chapter3finalredone.Models.DomainModels.WorkoutLog", "WorkoutLog")
                        .WithMany("WorkoutLogExercises")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.Exercise", b =>
                {
                    b.Navigation("WorkoutLogExercises");
                });

            modelBuilder.Entity("Chapter3finalredone.Models.DomainModels.WorkoutLog", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("WorkoutLogExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
