// <auto-generated />
using System;
using FitnessApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Migrations
{
    [DbContext(typeof(ExcersizeContext))]
    partial class ExcersizeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Models.ExerciseLog", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reps")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Workout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("ExerciseLog");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Activity = "Leg Day",
                            Reps = 8,
                            Sets = 3,
                            Weight = 200,
                            Workout = "Sqauts"
                        },
                        new
                        {
                            ExerciseId = 2,
                            Activity = "Upper Body",
                            Reps = 10,
                            Sets = 4,
                            Weight = 150,
                            Workout = "Push-Ups"
                        },
                        new
                        {
                            ExerciseId = 3,
                            Activity = "Upper Body",
                            Reps = 10,
                            Sets = 3,
                            Weight = 150,
                            Workout = "Dips"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
