// <auto-generated />
using CrackersPROJ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrackersPROJ.Migrations
{
    [DbContext(typeof(CrackerContext))]
    [Migration("20240706030713_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrackersPROJ.Models.Crackers", b =>
                {
                    b.Property<int>("CrackersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrackersId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Invented")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrackersId");

                    b.ToTable("Crackers");

                    b.HasData(
                        new
                        {
                            CrackersId = 1,
                            Calories = 200,
                            Invented = "1933",
                            Name = "Graham Crackers",
                            Price = "$2.00"
                        },
                        new
                        {
                            CrackersId = 2,
                            Calories = 500,
                            Invented = "1945",
                            Name = "Ritz",
                            Price = "$4.00"
                        },
                        new
                        {
                            CrackersId = 3,
                            Calories = 300,
                            Invented = "1950",
                            Name = "GoldFish",
                            Price = "$3.00"
                        },
                        new
                        {
                            CrackersId = 4,
                            Calories = 400,
                            Invented = "1960",
                            Name = "Saltine",
                            Price = "$4.50"
                        },
                        new
                        {
                            CrackersId = 5,
                            Calories = 500,
                            Invented = "1970",
                            Name = "Animal Crackers",
                            Price = "$5.00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
